### ISSUE TITLE
Description of PUT / POST template

### ISSUE THREAD

**Issue by jnehring** [freme-project/Documentation#25]
Please add to the description of endpoints POST /e-link/templates/ and PUT /e-link/templates/{template-id}

Example of input in JSON format:

```
{
    "query":"here goes the CONSTRUCT SPARQL query",
    "endpoint":"here goes the SPARQL endpoint. E.g., http://dbpedia.org/sparql/"
}
```

@freme-project/infai can you please provide an example in rdf / turtle? I could not find an example in the documentation.

**Comment by jnehring** [comment]
Wait for the example in rdf / turtle, integrate this in the documentation and then close the ticket.

**Comment by josauder** [comment]
Edit:Nevermind, wrong issue

**Comment by jnehring** [comment]
I think we can live without documentation of turtle so I leave it closed.
