### ISSUE TITLE
e-Terminology timeout response

### ISSUE THREAD

**Issue by josauder** [freme-project/Documentation#28]
Does not respond to API call made by Documentation
Also doesn't work with curl

{
  "timestamp": 1437470788126,
  "message": "java.net.SocketTimeoutException: Read timed out",
  "error": "Bad Gateway",
  "status": 502,
  "exception": "eu.freme.broker.exception.ExternalServiceFailedException",
  "path": "/e-terminology/tilde"
}

**Comment by jnehring** [comment]
We cant do anything here but wait for Tilde to speed up their API.
