### ISSUE TITLE
/e-publishing/html try it out doesn't work

### ISSUE THREAD

**Issue by josauder** [freme-project/Documentation#30]
File upload seems to not work, however curl with 

curl --form "htmlZip=@alice.zip" --form metadata='{   "titles":["Alice in Utopia","Alice in Europe"],   "authors":["Joske Vermeulen", "Nick Borth"],   "illustrators":["Frans Vervaacke", "John Riplosh"],   "creators":["Joske Vermeulen", "Nick Borth"],   "subjects":["alice", "rabbit"],   "coverImage":"cover.jpeg",   "language":"en",   "source":"",   "description":"This is the story about Alice in wonderland, involving a rabbit etc.",   "rights":"",   "identifier":{     "scheme":"",     "value":"urn:1235-568-2235"   },   "tableOfContents":[     {       "title":"Chapter 1",       "resource":"01.xhtml"     },     {       "title":"Chapter 2",       "resource":"02.xhtml"     }   ] }' http://api-dev.freme-project.eu/current/e-publishing/html > output.epub3

works fine

**Comment by jnehring** [comment]
The two parameters "htmlZip" and "metadata" need to be send in the body of the post request. The post request needs to be encoded as multipart request and metadata cannot be send via query strings. Thats actually whats your curl command does.

**Comment by josauder** [comment]
Documentation now transmits data. However, response is:

```
{"timestamp":1437658896626,"status":500,"error":"Internal Server Error","exception":"org.springframework.beans.ConversionNotSupportedException","message":"Failed to convert value of type 'org.springframework.web.multipart.support.StandardMultipartHttpServletRequest$StandardMultipartFile' to required type 'java.lang.String'; nested exception is java.lang.IllegalStateException: Cannot convert value of type [org.springframework.web.multipart.support.StandardMultipartHttpServletRequest$StandardMultipartFile] to required type [java.lang.String]: no matching editors or conversion strategy found","path":"/e-publishing/html"}
```
