### ISSUE TITLE
Create example of SKOS dataset

### ISSUE THREAD

**Issue by jnehring** [freme-project/Documentation#38]
Can you please paste a short SKOS dataset for FREME NER here into the GitHub issue? We will put it in the documentation. It will be part of http://api-dev.freme-project.eu/doc/ . We need it for the documentation of the calls
- POST /e-entity/freme-ner/datasets
- PUT /e-entity/freme-ner/datasets/{name}

**Comment by nilesh-c** [comment]
Example of SKOS dataset:

> http://www.lib.ncsu.edu/ld/onld/00000326 http://www.w3.org/2004/02/skos/core#:prefLabel "101 Communications" .
> http://www.lib.ncsu.edu/ld/onld/00000326 http://www.w3.org/2004/02/skos/core#:altLabel "101 Communications, Inc" .
> http://www.lib.ncsu.edu/ld/onld/00000326 http://www.w3.org/2004/02/skos/core#:altLabel "101 Communications, LLC" .
> http://www.lib.ncsu.edu/ld/onld/00000326 http://www.w3.org/2004/02/skos/core#:altLabel "101communications" .
> http://www.lib.ncsu.edu/ld/onld/00001273 http://www.w3.org/2004/02/skos/core#:prefLabel "2Cs Communications" .
> http://www.lib.ncsu.edu/ld/onld/00000842 http://www.w3.org/2004/02/skos/core#:prefLabel "2x4 (Design studio)" .

_NOTE 1:_
The properties  http://www.w3.org/2004/02/skos/core#:altLabel and http://www.w3.org/2004/02/skos/core#:prefLabel here are indexed (by default, skos:altLabel, skos:prefLabel, rdfs:label are indexed, please see docs). This is configurable. So even if it's blah:someOtherPredicate, we can support it through the properties parameter in FREME NER while dataset creation.

_NOTE 2:_
Something that should've been made clearer from the outset: SKOS datasets (see above, can even be non-skos labels as long as the user specifies them, but it's recommended to stick to skos/rdfs) are a minimum, they give us labels to build gazetteers from. But if the dataset providers have raw RDF with various other kinds of information (like location, geo-coordinates, sameAs, closeMatch etc.) they can include them too. So basically, send them all in. That will only help the entity linker in performing better disambiguation by taking into account inter-resource links.

**Comment by m1ci** [comment]
Hey,
the URI for the altLabel and prefLabel are wrong (note the colon char `:`). Correct URIs are:
http://www.w3.org/2004/02/skos/core#prefLabel
http://www.w3.org/2004/02/skos/core#altLabel

**Comment by jnehring** [comment]
Please update the documentation with example and notes. Put it in the POST request and refer to the example in the PUT request.
