### ISSUE TITLE
GET /e-link/templates/ escaping errors in all templates

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/Documentation#39]

**Comment by jnehring** [comment]
Please provide your request and also the response (or part of it when it is long).

**Comment by ArneBinder** [comment]
there is still code wrapped in <pre>```</pre>, should be wrapped with &lt;pre&gt;&lt;/pre&gt; and html encoded (e.g. via [this](http://www.opinionatedgeek.com/DotNet/Tools/HTMLEncode/Encode.aspx))

**Comment by ArneBinder** [comment]
This is just a bug in the documentation, there is no problem with the broker.

**Comment by jnehring** [comment]
There is a gray areay inside of the SPARQL queries which I believe is unnecessary. The SPARQL query in the picture starts with `PREFIX` and ends with `LIMIT 10`, so I believe there is no need for the gray area.

![image](https://cloud.githubusercontent.com/assets/10537540/8978264/cf2e0800-36a0-11e5-8f38-90590f6a80ec.png)

**Comment by ArneBinder** [comment]
fixed
