### ISSUE TITLE
Document e-Internationalization

### ISSUE THREAD

**Issue by jnehring** [freme-project/Documentation#41]
In the General section add under `informat`:
- `text/html`: Submit HTML as input. This will convert the HTML to NIF and then send it to the underlying service.
- `application/x-xliff+xml`: Submit XLIFF 1.2 as input. This will convert the XLIFF to NIF and then send it to the underlying service.

Then add the two Content-Types to the `Parameter content type` section of each enrichment endpoint.

**Comment by josauder** [comment]
Done

**Comment by jnehring** [comment]
Thats odd because I cannot see the changes on http://api-dev.freme-project.eu/doc . We had this kind of errors quite often and I dont know whats going on. Maybe you have a problem with Git? Please do it again. And please check for every change you do in the documentation if you can see the check on the homepage. You should also try it via the API tester before closing the ticket.

**Comment by jnehring** [comment]
Only enrichment endpoints support this informat / Content-Type header. These endpoints are
- POST /e-entity/dbpedia-spotlight/documents
- POST /e-entity/freme-ner/documents
- POST /e-link/documents/
- POST /e-terminology/tilde
- POST /e-translation/tilde

Please delete `text/html` and `application/x-xliff+xml` from all other `informat` and `Content-Type` dropdowns.
