### ISSUE TITLE
Improve /e-link examples

### ISSUE THREAD

**Issue by jnehring** [freme-project/Documentation#43]
We have a bugreport that the examples in the API doc for some e-link templates do not work.

`only 2 and 3 worked for Frank, 7 gave an exception for e-Link`

Please test all e-link templates and try to find better examples when there is a mistake.

**Comment by ArneBinder** [comment]
For template/example 1 and 5 it's the same for me. But 6 works via curl. There is no possibility to set an user defined parameter via the try-out button of the documentation page. This is used by template nr 6 (marked by @@@), have a look at **event_type** in the example curl call:  `curl -v -X POST -d @test-for-template-6.ttl "http://api-dev.freme-project.eu/current/e-link/documents/?outformat=turtle&templateid=6&event_type=SocietalEvent" -H "Content-Type: text/turtle"` 

@jnehring To enable this, we had to modify the javascript files of the documentation aka switch to the other branch ;-)

Template 7: works with none of the given examples, so i assume there is really an error in the uploaded template.

@m1ci are the examples 1 and 5 working for you? If not, perhaps do you have some alternatives? And is there really an error in template 7? Thanks!

**Comment by jnehring** [comment]
> There is no possibility to set an user defined parameter via the try-out button of the documentation page.

I added this to the work package [changing the api doc template](https://docs.google.com/document/d/1oXd0RYFvd4B22avUMRVJrTYt-7tJ35Bm6tes0hwC398/edit#)

> Template 7: works with none of the given examples, so i assume there is really an error in the uploaded template.

I could reproduce the problem and created bug report freme-project/e-Link#39

> are the examples 1 and 5 working for you? If not, perhaps do you have some alternatives? And is there really an error in template 7? Thanks!

Moved to freme-project/e-Link#40

Thanks @ArneBinder for the good work!
