### ISSUE TITLE
e-Translation supported language pairs

### ISSUE THREAD

**Issue by borriellom** [freme-project/Documentation#48]
This is just a suggestion for improving the documentation. The e-Translation documentation displays two combos listing source and target languages. The source language combo lists some unsupported source languages ( de, fr, it, es). I'm aware that the description field properly redirects to the Tilde web page containing allowed pairs. Anyway that source combo is misleading for the user.

**Comment by jnehring** [comment]
I think the combo boxes are misleading because they suggest that you can use any combination of source language and target language. I suggest we replace the combo boxes with text input boxes `<input .../>`.

**Comment by josauder** [comment]
@jnehring what do you mean?

**Comment by jnehring** [comment]
I mean that users can enter the languages themselves as free text and there are no select boxes. But leave it like it is for this release, in FREME 0.4 we can work it over.

**Comment by josauder** [comment]
@jnehring I can also implement this now. It should not take long

**Comment by jnehring** [comment]
please implement it for e-translation and e-terminology.
