### ISSUE TITLE
improve e-Link documentation

### ISSUE THREAD

**Issue by m1ci** [freme-project/Documentation#49]
Current description

> Update an enrichment template with specified ID. The new data is submitted as body of a PUT request.

However, the PUT operation updates or creates a template if the template is not available.
Please update the description to:

> Update or creates an enrichment template (if it does not exist) with specified ID. The new data is submitted as body of a PUT request.

This relates to the question https://github.com/freme-project/e-Link/issues/31

**Comment by jnehring** [comment]
Also update description of PUT / POST /e-link/templates
- Please remove all `informat` and `Content-Type` values  except `application/json` and all outformats except `application/json` and `turtle`. We do not have documentation for these so they are confusing. Also update the descriptions.
- Please remove the example from PUT and refer to the POST endpoint for further documentation on the format of a template. Can you create a hyperlink to the POST endpoint?
- Change the example in POST:

```
 {
 "query":"here goes the CONSTRUCT SPARQL query",
 "endpoint":"here goes the SPARQL endpoint. E.g., http://dbpedia.org/sparql/",
 "label": "the title of the template",
 "description": "a description of the template"
 }
```

**Comment by m1ci** [comment]
Provide description of a template. Description of the:
- `label`: the name of the template
- `description`: a short description describing the template
- `query`: a SPARQL CONSTRUCT query
- `endpoint`: a SPARQL endpoint which will be used to execute the template
