### ISSUE TITLE
Confidence parameter /e-entity/dbpedia-spotlight/documents

### ISSUE THREAD

**Issue by jnehring** [freme-project/Documentation#50]
Please provide better documentation for the confidence parameter in `POST /e-entity/dbpedia-spotlight/documents`.
- What is the range of the parameter? Is it a value between 0 and 1?
- Please add a description like `A low confidence value returns a small amount of entity annotations that have high precision. A high confidence value returns many entity annotations with low precision.` Correct the sentence when it is wrong.

**Comment by m1ci** [comment]
from the description of the DBpedia spotlight paper: http://blog.semantic-web.at/wp-content/uploads/2011/09/p1_mendes.pdf the description of the `confidence` parameter can be summarized as: 

`Setting a high confidence threshold instructs DBpedia Spotlight to avoid incorrect annotations as much as possible at the risk of losing some correct ones.  A confidence value of 0.7 will eliminate 70% of incorrectly disambiguated test cases.
The range of the confidence parameter is between 0 and 1.`

**Comment by jnehring** [comment]
Thanks @m1ci . @ArneBinder  please update the Documentation.
