### ISSUE TITLE
Documentation of POST /e-link/documents

### ISSUE THREAD

**Issue by jnehring** [freme-project/Documentation#61]
Remove `Response Content Type` value `application/json`

Remove `Parameter content type` values `application/json`, `text/html`, `application/x+xliff+xml`

**Comment by ArneBinder** [comment]
Done. @jnehring does this hold also for informat and outformat?

**Comment by jnehring** [comment]
Yes thanks for "mitdenken". Please update informat and outformat also.

**Comment by ArneBinder** [comment]
Fixed.
