### ISSUE TITLE
Try out GitHub pages on the sample project

### ISSUE THREAD

**Issue by jnehring** [freme-project/Documentation#64]
Render the sample project from #63 via GitHub pages. Try out

1st to use GitHub pages to show the development version of the sample project and find a way to download the compiled version of the sample project to create a release for the live homepage.

When 1st does not work out then try to have two separate github pages in one repository.

**Comment by josauder** [comment]
We will not host on github-pages because they do not allow a plugin which makes jekyll a lot more convenient to use ( the plugin contains all html files in a good folder structure instead of scattering them in the parent directory). Github writes:

```

Plugins on GitHub Pages

GitHub Pages is powered by Jekyll. However, all Pages sites are generated using the --safe option to disable custom plugins for security reasons. Unfortunately, this means your plugins won’t work if you’re deploying to GitHub Pages.

You can still use GitHub Pages to publish your site, but you’ll need to convert the site locally and push the generated static files to your GitHub repository instead of the Jekyll source files.
```
