### ISSUE TITLE
Implement simple API documentation

### ISSUE THREAD

**Issue by jnehring** [freme-project/Documentation#67]
Implement an API documentation that contains only these endpoints:

POST /e-entity/dbpedia-spotlight/documents
POST /e-entity/freme-ner/documents
POST /e-link/documents
POST /e-publishing/html
POST /e-terminology/tilde
POST /e-translation/tilde
POST /pipelining/chain

It should be created from the big yaml file with all endpoints so we do not maintain two separate yaml files.

**Comment by josauder** [comment]
Closed, see #65
