### ISSUE TITLE
Include General Info on broad topics?

### ISSUE THREAD

**Issue by josauder** [freme-project/Documentation#69]
in https://docs.google.com/document/d/1td27IdoQUSvsu3UYCGmj6GWdKU73YTp_oeRG5zfwF7w/edit# you mentioned that some points have a general information.

Example:

```

API documentation
--------------------------

    This web page documents the REST API of the FREME project. 

    To make it easier to understand the content of this documentation, this section 
    has been separated in   two  different pages: the simple [LINK] documentation 
    which contains only the most important endpoints and the extensive [LINK] version 
    that contains all endpoints and the full API documentation. We advise new users to
     use the simple documentation at first.

```

However, with the way that the navigation bar works (in order to support mobile browsers where no mouseover exists) it only makes sense that the dropdowns open on click.

Like this:
![screenshot from 2015-09-23 17 14 02](https://cloud.githubusercontent.com/assets/12648328/10049211/c7f8b5ac-6216-11e5-91b7-3bf06a8dd5a5.png)

One could make an additional subpoint in this dropdown menu only to display the general information, or we leave it out. Thoughts?

**Comment by jnehring** [comment]
I suggest to have the first page in the menu called "Overview" in the case of FREME showroom. What do you think @josauder

**Comment by josauder** [comment]
I think either we add a first "overview" page to every dropdown or to none, but I think we should be consistent with our choice.

**Comment by jnehring** [comment]
Later on we will implement an overview page. But we will create these overview pages in the end.
