### ISSUE TITLE
Set document index

### ISSUE THREAD

**Issue by jnehring** [freme-project/Documentation#79]
Right now there is a redirect implemented to make start.html the start page. Please remove that redirect and create a .htaccess file that sets the directory index.

Some documentation: http://davidwalsh.name/directory-index-homepage-htaccess

**Comment by jnehring** [comment]
```
DirectoryIndex start.html
```

**Comment by josauder** [comment]
Oops typo. Fixed with 5e6904daea57b84ee4368e3745b5e87782042c55
