### ISSUE TITLE
Swagger validator fails on documentation

### ISSUE THREAD

**Issue by jnehring** [freme-project/Documentation#9]
I disabled the validator in the version online for freme 0.2 adding `validatorUrl: null` in index.html, line 30

**Comment by josauder** [comment]
In which file did you disable the validator? /Documentation/index does not include any line concerning validatorUrl. @jnehring

**Comment by jnehring** [comment]
The disabled validator was never checked in the github repository, i disabled it in freme-live after the release: http://api.freme-project.eu/doc/0.2

However I dont like that button. We should disable it by default and only use it to validate our documentation before a release.
